# Generated by Django 5.2.2 on 2025-06-10 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("disasters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("gender", models.CharField(max_length=1)),
                ("nickname", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                ("login_id", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=300)),
                ("email", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                (
                    "city",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="disasters.citycategory",
                    ),
                ),
            ],
        ),
    ]
