# Generated by Django 5.2.2 on 2025-06-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="nickname",
        ),
    ]
