# Generated by Django 5.2.2 on 2025-06-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
                ("url", models.TextField()),
                ("source_name", models.CharField(max_length=255)),
                ("source_url", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("crawl_time", models.DateTimeField()),
                ("crawl_status", models.CharField(max_length=50)),
                ("error_message", models.TextField()),
            ],
        ),
    ]
