# Generated by Django 5.2.2 on 2025-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="crawl_time",
            field=models.DateField(),
        ),
    ]
