services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file: ../../.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  web:
    build:
      context: ../../api
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../../api:/app
      - ../../web:/web
    ports:
      - "8000:8000"
    env_file: ../../.env
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../../web/src:/usr/share/nginx/html/src
      - ../../web/static:/usr/share/nginx/html/static
      - ../../web/media:/usr/share/nginx/html/media
    depends_on:
      - web

volumes:
  mysql-data:
