# Generated by Django 5.2.2 on 2025-06-10 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsuranceHistory",
            fields=[
                ("history_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("regster_date", models.DateField()),
                ("pub_pri", models.IntegerField()),
                ("insurance_id", models.BigIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrivateInsurance",
            fields=[
                (
                    "insurance_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("policy_id", models.IntegerField()),
                ("insurance_company_name", models.CharField(max_length=100)),
                ("insurance_name", models.CharField(max_length=100)),
                ("policy_type", models.CharField(max_length=50)),
                (
                    "coverage_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("premium", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PulicInsurance",
            fields=[
                (
                    "insurance_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("insurance_name", models.CharField(max_length=50)),
                ("coverage_type", models.CharField(max_length=30)),
                ("description", models.TextField()),
                (
                    "gov_support_info",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("gov_site", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.user"
                    ),
                ),
            ],
        ),
    ]
