# Generated by Django 5.2.3 on 2025-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pulicinsurance',
            name='gov_support_info',
        ),
        migrations.RemoveField(
            model_name='pulicinsurance',
            name='user',
        ),
        migrations.AddField(
            model_name='pulicinsurance',
            name='city_name',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulicinsurance',
            name='coverage_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulicinsurance',
            name='end_date',
            field=models.DateField(default='2222-02-02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulicinsurance',
            name='manage_department',
            field=models.CharField(default='0', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulicinsurance',
            name='manage_phone',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pulicinsurance',
            name='start_date',
            field=models.DateField(default='2222-02-02'),
            preserve_default=False,
        ),
    ]
