# Generated by Django 5.2.2 on 2025-06-10 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CityCategory",
            fields=[
                ("city_id", models.AutoField(primary_key=True, serialize=False)),
                ("city_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DisasterCategory",
            fields=[
                ("category_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("pictogram_image", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DisasterDetail",
            fields=[
                ("disaster_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("occurrence_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("scale", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disasters.disastercategory",
                    ),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disasters.citycategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisasterProtocol",
            fields=[
                ("protocol_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("guide_url", models.CharField(max_length=100)),
                (
                    "disaster_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disasters.disastercategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agency",
            fields=[
                ("agency_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("contact", models.CharField(max_length=20)),
                ("type", models.CharField(max_length=20)),
                (
                    "protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disasters.disasterprotocol",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Responder",
            fields=[
                ("reponder_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("role", models.CharField(max_length=20)),
                ("contact", models.CharField(max_length=20)),
                (
                    "agency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disasters.agency",
                    ),
                ),
            ],
        ),
    ]
