# Generated by Django 5.2.2 on 2025-06-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disasters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiDataset",
            fields=[
                ("dataset_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField()),
                ("exmn_hmty", models.FloatField(blank=True, null=True)),
                ("exmn_tp", models.FloatField(blank=True, null=True)),
                ("weather", models.CharField(max_length=6)),
                ("fire_check", models.BooleanField(default=False)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disasters.citycategory",
                    ),
                ),
            ],
        ),
    ]
