# Generated by Django 5.2.2 on 2025-06-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disasters", "0002_aidataset"),
    ]

    operations = [
        migrations.RenameField(
            model_name="citycategory",
            old_name="city_name",
            new_name="city_name1",
        ),
        migrations.AddField(
            model_name="citycategory",
            name="city_name2",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
