# Generated by Django 5.2.2 on 2025-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disasters", "0003_rename_city_name_citycategory_city_name1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aidataset",
            name="time",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="disasterdetail",
            name="end_time",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="disasterdetail",
            name="occurrence_time",
            field=models.DateField(),
        ),
    ]
