# Generated by Django 5.2.3 on 2025-06-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0004_alter_aidataset_time_alter_disasterdetail_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasterdetail',
            name='casualty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disasterdetail',
            name='caused',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
