# Generated by Django 5.2.3 on 2025-06-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0005_disasterdetail_casualty_disasterdetail_caused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasterdetail',
            name='casualty',
            field=models.IntegerField(default=0),
        ),
    ]
