# Generated by Django 5.2.3 on 2025-06-23 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0006_alter_disasterdetail_casualty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disasterdetail',
            name='end_time',
        ),
    ]
